################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE:           prestashop
  MYSQL_ROOT_PASSWORD:      admin
  DOCKER_DRIVER:            overlay2
  COMPOSER_MEMORY_LIMIT:    -1
  TMP_DIR:                  /builds/splashsync-modules/Prestashop
  SCRIPTS_DIR:              /builds/splashsync-modules/Prestashop/travis
  TRAVIS_BUILD_DIR:         /var/www/html
  DB_SERVER:                mysql
  PS_INSTALL_AUTO:          1
  SPLASH_NO_APACHE:         1
  SPLASH_WS_ID:             ThisIsPsLastKey
  SPLASH_WS_KEY:            ThisTokenIsNotSoSecretChangeIt
  SPLASH_WS_HOST:           http://test.splashsync.local/ws/soap

################################################################
# Defined Pipeline Stages
stages:
  - tests

before_script:
  - apt-get update
  - apt-get install -y zip unzip git
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - php -r "unlink('composer-setup.php');"
  - echo "memory_limit=-1" >> /usr/local/etc/php/conf.d/memeory.ini

################################################################
# Functional Tests
################################################################

tests:
    image:      prestashop/prestashop:1.7-7.2-apache
    stage:      tests
    tags:       ['Dedicated']
    script:

      - cd $TMP_DIR

      ################################################################################
      # Build Module (Composer)
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/composer.sh | sh
#      - ls -l $CI_PROJECT_DIR
#      - ls -la $TMP_DIR
#      - php modules/splashsync/vendor/bin/grumphp run -n --testsuite=travis
#      - ls -l $TRAVIS_BUILD_DIR

      ################################################################################
      # Install Prestashop + WebServer (Apache & PHP-Fpm)
      - cat $CI_PROJECT_DIR/docker/docker-entrypoint.sh | bash

      ################################################################################
      # Install Module
      - bash $SCRIPTS_DIR/module/install.sh

      ################################################################################
      # Run Grumphp Main Test Sequence
      - cd $TMP_DIR
      - php modules/splashsync/vendor/bin/grumphp run -n --testsuite=travis

      ################################################################################
      # Run Grumphp CsFixer Test Sequence
      - cd $TRAVIS_BUILD_DIR
      - composer install
      - php modules/splashsync/vendor/bin/grumphp run -n --testsuite=csfixer

      ################################################################################
      # Run Grumphp Phpstan Test Sequence
      - php modules/splashsync/vendor/bin/grumphp run -n --testsuite=phpstan

      ################################################################################
      # Run PhpUnit Core Test Sequence (Will Enable the Module)
      - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist modules/splashsync/vendor/splash/phpcore/Tests/Core/

      ################################################################################
      # ALL PHP   =>  Run PhpUnit Local Sequence with No Data Inside
      - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist --testsuite=Local

      ################################################################################
      # Run PhpUnit Test Sequence (With Coverage)
      - php modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist

      ################################################################################
      # Run PhpUnit Product with MSF Sequence
      - php travis/setup_shops.php && php travis/setup_shops.php
      - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.products.xml
#      - bash $SCRIPTS_DIR/module/setup.sh

#        # Composer Build
#        - cat  travis/composer.sh | sh
#        # Execute Grump Travis Testsuite
#        - cat travis/grumphp.sh | sh
#    after_script:
#        # Run After Script
#        - cat  travis/after.sh | sh

    services:
      - name: mysql:5.7
