################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE:           prestashop
  MYSQL_ROOT_PASSWORD:      admin
  DOCKER_DRIVER:            overlay2
  COMPOSER_MEMORY_LIMIT:    -1
  TMP_DIR:                  /builds/splashsync-modules/Prestashop
  SCRIPTS_DIR:              /builds/splashsync-modules/Prestashop/travis
  TRAVIS_BUILD_DIR:         /var/www/html
  DB_SERVER:                mysql
  PS_INSTALL_AUTO:          1
  SPLASH_NO_APACHE:         1
  SPLASH_WS_ID:             ThisIsPsLastKey
  SPLASH_WS_KEY:            ThisTokenIsNotSoSecretChangeIt
  SPLASH_WS_HOST:           http://test.splashsync.local/ws/soap

################################################################
# Defined Pipeline Stages
stages:
  - tests

before_script:
  - apt-get update
  - apt-get install zip unzip
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"

################################################################
# Functional Tests
################################################################

tests:
    image:      prestashop/prestashop:1.7-7.2-apache
    stage:      tests
    tags:       ['Dedicated']
    script:
      - cd $TMP_DIR
      # Setup Environnement
#      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/configure.sh | sh
      # Build Module (Composer)
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/composer.sh | sh
#      - ls -l $CI_PROJECT_DIR
      - ls -l $TMP_DIR
#      - ls -l $TRAVIS_BUILD_DIR
#      - cat $CI_PROJECT_DIR/docker/docker-entrypoint.sh | bash
#        # Composer Build
#        - cat  travis/composer.sh | sh
#        # Execute Grump Travis Testsuite
#        - cat travis/grumphp.sh | sh
#    after_script:
#        # Run After Script
#        - cat  travis/after.sh | sh

    services:
      - name: mysql:5.7
