################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Travis CI Configuration File
################################################################################

# Tell Travis CI we're using PHP
language: php

addons:
    #chrome: stable
    apt:
        packages:
        - apache2
        - postfix
        - libapache2-mod-fastcgi
        - libappindicator1
        - fonts-liberation

cache:
  directories:
    - $HOME/.composer/cache

os: linux
dist: trusty

jobs:
    include:
        
        # Prestashop develop Branch       
#        - php: 7.3
#          env: PS_VERSION=develop
#        - php: 7.1
#          env: PS_VERSION=develop

        # Prestashop 1.7.7.x Branch
        - php: 7.3
          env: PS_VERSION=1.7.7.x
#        - php: 7.2
#          env: PS_VERSION=1.7.7.x
        - php: 7.1
          env: PS_VERSION=1.7.7.x

        # Prestashop 1.7.6.x Branch
        - php: 7.3
          env: PS_VERSION=1.7.6.x

        # Prestashop 1.7.5.x Branch
        - php: 7.2
          env: PS_VERSION=1.7.5.x

        # Prestashop 1.7.4.x Branch
        - php: 7.1
          env: PS_VERSION=1.7.4.x

        # Prestashop 1.7.1.x Branch
        - php: 7.1
          env: PS_VERSION=1.7.1.x
        
    allow_failures:
#        - env: PS_VERSION=1.7.5.x
        - env: PS_VERSION=develop
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true

# Global Env Configuration
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
        - GRUMPHP_BIN_DIR="modules/splashsync/vendor/bin"
        
before_script:

    - export MODULE_DIR=/tmp/SplashSync
    - export MODULE_SCRIPTS_DIR=/tmp/SplashSync/travis

    #   Move Module to Tmp Folder
    - bash travis/move_module.sh
    #   Install Prestashop
    - bash $MODULE_SCRIPTS_DIR/install_prestashop.sh
    #    Setup WebServer (Apache & PHP-Fpm)
    - bash $MODULE_SCRIPTS_DIR/install_webserver.sh
    #   Start Prestashop (Composer & More)
    - bash $MODULE_SCRIPTS_DIR/start_prestashop.sh
    #   Install Module
    - bash $MODULE_SCRIPTS_DIR/install_module.sh
    
script: 
    - cd $MODULE_DIR
    
    # Run Grump Main Test Sequence
    - php modules/splashsync/vendor/bin/grumphp run --testsuite=travis
    - cd $TRAVIS_BUILD_DIR

    # With PHP 7.2 => Execute CsFixer
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.1" ]]; then php modules/splashsync/vendor/bin/grumphp run --testsuite=csfixer; fi
    # With PHP 7.2 => Execute Phpstan 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.1" ]]; then php modules/splashsync/vendor/bin/grumphp run --testsuite=phpstan; fi
    
    # Run PhpUnit Core Test Sequence (Will Enable the Module)
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist modules/splashsync/vendor/splash/phpcore/Tests/Core/
    
    # ALL PHP   =>  Run PhpUnit Local Sequence with No Data Inside
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist --testsuite=Local
    
    # PHP7+     =>  Run PhpUnit Main Sequence
    - if [[ ${TRAVIS_PHP_VERSION:0:1} > "5" ]]; then phpdbg -qrr -d memory_limit=-1 modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist; fi
    # PHP5.6    =>  Without Php Debugger (Coverage x2 Faster)
    - if [[ ${TRAVIS_PHP_VERSION:0:1} < "7" ]]; then modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist; fi

    ################################################################################
    # Run PhpUnit Product with MSF Sequence
    ################################################################################
    # Start Prestashop (Composer & More)
    - bash $MODULE_SCRIPTS_DIR/start_prestashop.sh
    # Install Module
    - bash $MODULE_SCRIPTS_DIR/install_module.sh
    # Enable MSF Mode
    - cd $TRAVIS_BUILD_DIR
    - php travis/setup_shops.php && php travis/setup_shops.php
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist --testsuite=Local
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.products.xml modules/splashsync/vendor/splash/phpcore/Tests/WsAdmin
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.products.xml modules/splashsync/vendor/splash/phpcore/Tests/WsObjects
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.products.xml modules/splashsync/vendor/splash/phpcore/Tests/WsSpecials

    # Show Outdated Packages
    - cd $MODULE_DIR    
    - composer outdated -D
    
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

after_success:
    # Display Full List of Executed Tests    
    - cat coverage/executed.txt
    
after_failure:
