################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Travis CI Configuration File
################################################################################

jobs:
    include:
        
        # Prestashop develop Branch       
#        - php: 7.3
#          env: PS_VERSION=develop
#        - php: 7.1
#          env: PS_VERSION=develop

        # Prestashop 1.7.7.x Branch
        - php: 7.4
          env: PS_VERSION=1.7.7.x
        - php: 7.2
          env: PS_VERSION=1.7.7.x

        # Prestashop 1.7.6.x Branch
        - php: 7.3
          env: PS_VERSION=1.7.6.x

        # Prestashop 1.7.5.x Branch
        - php: 7.2
          env: PS_VERSION=1.7.5.x

        # Prestashop 1.7.4.x Branch
        - php: 7.3
          env: PS_VERSION=1.7.4.x

        # Prestashop 1.7.1.x Branch
        - php: 7.2
          env: PS_VERSION=1.7.1.x
        
    allow_failures:
        - env: PS_VERSION=develop
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true



################################################################################
# TEST SCRIPTS
################################################################################

################################################################################
# Install & Configure Environnement
before_install:
  - bash travis/before.sh

################################################################################
# Install & Configure Environnement
install:

    ################################################################################
    # Setup Travis
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/configure.sh | sh
    # Build Module (Composer)
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/travis/composer.sh | sh
    # Move Module to Tmp Folder
    - bash travis/module/move.sh

    ################################################################################
    # Install Prestashop + WebServer (Apache & PHP-Fpm)
    - bash $SCRIPTS_DIR/prestashop/install.sh

    ################################################################################
    # Install Module
    - bash $SCRIPTS_DIR/module/install.sh
    - bash $SCRIPTS_DIR/module/setup.sh

################################################################################
# Run Test Script
script: 

    # Run Grumphp Main Test Sequence
    - cd $TMP_DIR
    - php modules/splashsync/vendor/bin/grumphp run -n --testsuite=travis

    - cd $TRAVIS_BUILD_DIR

    # Run Grumphp CsFixer Test Sequence
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.1" ]]; then php modules/splashsync/vendor/bin/grumphp run -n --testsuite=csfixer; fi
    # Run Grumphp Phpstan Test Sequence
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.1" ]]; then php modules/splashsync/vendor/bin/grumphp run -n --testsuite=phpstan; fi

    # Run PhpUnit Core Test Sequence (Will Enable the Module)
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist modules/splashsync/vendor/splash/phpcore/Tests/Core/
    
    # ALL PHP   =>  Run PhpUnit Local Sequence with No Data Inside
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist --testsuite=Local
    
    # Run PhpUnit Test Sequence (With Coverage)
    # - if [[ ${TRAVIS_PHP_VERSION:0:1} > "5" ]]; then phpdbg -qrr -d memory_limit=-1 modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist; fi
    # Run PhpUnit Test Sequence (NO Coverage)
    - php modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist

    # Run PhpUnit Product with MSF Sequence
    - php travis/setup_shops.php && php travis/setup_shops.php
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.products.xml

    # Show Outdated Packages
    - cd $MODULE_DIR    
    - composer outdated -D

################################################################################
# Run After Script
after_script:
  - cd $TMP_DIR
  - bash $SCRIPTS_DIR/after.sh

################################################################################
# GENERIC CONFIGURATION
################################################################################

################################################################################
# Project language
language:   php
os:         linux
dist:       trusty

################################################################################
# Tell Travis CI we're using MySQL
services:
  - mysql

################################################################################
# Tell Travis CI we're using Cache
cache:
  directories:
    - $HOME/.composer/cache

################################################################################
# Global Env Configuration
env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=disabled
    - GRUMPHP_BIN_DIR="modules/splashsync/vendor/bin"
    - TMP_DIR=/tmp/SplashSync
    - SCRIPTS_DIR=/tmp/SplashSync/travis

################################################################################
# Tell Travis CI we're using Addons
addons:
  apt:
    packages:
      - apache2
      - postfix
      - libapache2-mod-fastcgi
      - libappindicator1
      - fonts-liberation

################################################################################
# After a build, send email notification with the build results
notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
